# Generated by Django 2.0.2 on 2019-03-03 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('degreeID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degreeID', models.AutoField(primary_key=True, serialize=False)),
                ('degreeName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('linksID', models.IntegerField(primary_key=True, serialize=False)),
                ('linkName', models.CharField(max_length=100)),
                ('topicID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progressID', models.IntegerField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('linkID', models.IntegerField()),
                ('isCompleted', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=100)),
                ('courseID', models.IntegerField()),
                ('references', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('degreeID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='references',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Users'),
        ),
        migrations.AddField(
            model_name='links',
            name='references',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Topics'),
        ),
        migrations.AddField(
            model_name='courses',
            name='references',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Degree'),
        ),
    ]
