# Generated by Django 2.0.2 on 2019-03-27 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(default='default description', max_length=400)),
                ('courseLink', models.CharField(default='links/', max_length=100)),
                ('level', models.CharField(default='Freshman', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degreeID', models.AutoField(primary_key=True, serialize=False)),
                ('degreeName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('linksID', models.AutoField(primary_key=True, serialize=False)),
                ('linkName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progressID', models.IntegerField(primary_key=True, serialize=False)),
                ('isCompleted', models.BooleanField()),
                ('notes', models.TextField()),
                ('linkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=100)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('degreeID', models.IntegerField()),
                ('user', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Users'),
        ),
        migrations.AddField(
            model_name='links',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Topics'),
        ),
        migrations.AddField(
            model_name='courses',
            name='degreeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Degree'),
        ),
    ]
