# Generated by Django 2.0.2 on 2019-03-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseDescription',
            field=models.CharField(default='default description', max_length=400),
        ),
        migrations.AddField(
            model_name='courses',
            name='courseLink',
            field=models.CharField(default='links/', max_length=100),
        ),
    ]
