# Generated by Django 2.0.2 on 2019-03-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seniorProjectApp', '0003_auto_20190315_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='references',
        ),
        migrations.RemoveField(
            model_name='links',
            name='references',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='references',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='references',
        ),
        migrations.AlterField(
            model_name='courses',
            name='degreeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Degree'),
        ),
        migrations.AlterField(
            model_name='links',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Topics'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='linkID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Links'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Users'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorProjectApp.Courses'),
        ),
    ]
